services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      MONGODB: "mongodb://mongodb:27017"
      DB_NAME: "${DB_NAME}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - action: sync
          path: .
          target: ./code
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: <admin-password>
#      MONGO_INITDB_DATABASE: <database to create>
    ports:
      - '27017:27017'